require:
  - rubocop-performance
  - rubocop-rspec

inherit_gem:
  rentacop: rentacop.yml

AllCops:
  TargetRubyVersion: 2.6
  SuggestExtensions: false

# Allow some methods to start with `set_` or `get_`
Naming/AccessorMethodName:
  Exclude:
    - 'lib/audio_addict/commands/config.rb'
    - 'lib/audio_addict/commands/set.rb'

# Allow long lines in command DSL
Layout/LineLength:
  Exclude:
    - "lib/audio_addict/commands/**/*"

# Prefer `receive` over `have_received` spies
RSpec/MessageSpies:
  EnforcedStyle: receive

# Allow top level `describe` to include arbitrary text in some cases
RSpec/DescribeClass:
  Exclude:
    - spec/audio_addict/commands/commands_spec.rb
    - spec/audio_addict/bin_errors_spec.rb

# Allow stubbing other `subject` methods
RSpec/SubjectStub:
  Enabled: false

# Allow nameless `subject`
RSpec/NamedSubject:
  Enabled: false

# Allow higher metrics
RSpec/ExampleLength:
  Max: 17
RSpec/MultipleExpectations:
  Max: 4
RSpec/NestedGroups:
  Max: 4

