require:
  - rubocop-performance
  - rubocop-rspec

inherit_gem:
  rentacop:
    - rentacop.yml
    - rspec.yml

AllCops:
  TargetRubyVersion: 2.6
  SuggestExtensions: false

# Allow some methods to start with `set_` or `get_`
Naming/AccessorMethodName:
  Exclude:
    - 'lib/audio_addict/commands/config.rb'
    - 'lib/audio_addict/commands/set.rb'

# Allow long lines in command DSL
Layout/LineLength:
  Exclude:
    - "lib/audio_addict/commands/**/*"

# Allow longer examples
RSpec/ExampleLength:
  Max: 17

# Allow `expect` for configuring response in some cases
RSpec/StubbedMock:
  Exclude:
    - spec/audio_addict/youtube_spec.rb
